print("selamat datang kalkulator sederhana.")
print("ketik 1 untuk menghitung penjumlahan.")
print("ketik 2 untuk menghitung pengurangan.")
print("ketik 3 untuk menghitung perkalian.")
print("ketik 4 untuk menghitung pembagian.")
print("ketik 5 untuk menghitung sisa hasil bagi(modulus).")
print("ketik 6 untuk menghitung pemangkatan.")
pilihan = input("masukan pilhan anda: ")
pilhanbil = input("masukan bilangan pertama: ")
pilhanbil3= input("masukkan bilangan kedua: ")

print("selamat datang kalkulator sederhana.")
print("ketik 1 untuk menghitung penjumlahan.")
print("ketik 2 untuk menghitung pengurangan.")
print("ketik 3 untuk menghitung perkalian.")
print("ketik 4 untuk menghitung pembagian.")
print("ketik 5 untuk menghitung sisa hasil bagi(modulus).")
print("ketik 6 untuk menghitung pemangkatan.")
pilihan = input("masukan pilhan anda: ")
pilhanbil = input("masukan bilangan pertama: ")
pilhanbil3= input("masukkan bilangan kedua: ") 



nn = input("masukkan tahun:")